### ISSUE TITLE
Broken Side Effect: Copy to Clipboard

### ISSUE THREAD

**Issue by merchako** [usfm-bible/docs.usfm.bible#3]
Problem steps
1. Find an [example component](https://docs.usfm.bible/usfm/3.1/char/features/em.html#_examples)
2. Click the Copy to Clipboard Icon

![Screenshot of an example component with the mouse hovering the clipboard icon and the tooltip "Copy to Clipboard"](https://github.com/user-attachments/assets/935f9926-ab87-4d6a-9e97-5430a7d1cd18)

Notice that 
* You see an expanded lightbox of the icon
* There's no indication that the copy-to-clipboard worked
* The contents of the example are indeed in your clipboard

Solution
1. Don't show the lightbox
2. Show a snackbar indicating that the content of the example is now on the user's clipboard

**Comment by klassenjm** [comment]
I believe this issue is resolved. The zoom is now only being applied to block level images, not inline.
